# Build Docker image for this app
# https://docs.microsoft.com/vsts/pipelines/languages/docker?view=vsts

queue: 'Hosted Linux Preview'

variables:
  imageName: '$(Build.DefinitionName):$(Build.BuildId)'
  # define two more variables dockerId and dockerPassword in the build pipeline in UI

steps:
- script: |
    npm install
    npm test
    docker build -t $(dockerId)/$(imageName) .
    docker login -u $(dockerId) -p $pswd
    docker push $(dockerId)/$(imageName)
  env:
    pswd: $(dockerPassword)

- task: PublishTestResults@2
  inputs:
    testRunner: JUnit
    testResultsFiles: '**/TEST-RESULTS.xml'
